function [ stLabelNames ] = LabelNames( FileName,NUMAXLES )

    fID = fopen(FileName,'r');                              %Open FileName
    fileHEADERLINE = textscan(fID,'%s',1,'Delimiter','\n'); %Pull off headerline
    headerSTRINGCELL = char(fileHEADERLINE{:});             %Turn Cell into String
    delimHEADER = strsplit(headerSTRINGCELL,',');           %Split String at Delimiter
    stLabelNames.Labels = strtrim(delimHEADER);             %Truncate Extra Spaces

    
    %Engine Outputs
        stLabelNames.AV_Eng_Index = find(strcmp('AV_Eng',stLabelNames.Labels));     %Find AV_Eng in Data (rpm)
        stLabelNames.M_Eng_In_Index = find(strcmp('M_Eng_In',stLabelNames.Labels)); %Find M_Eng_In in Data (N-m)
        stLabelNames.M_EngOut_Index = find(strcmp('M_EngOut',stLabelNames.Labels)); %Find M_EngOut in Data (N-m)
        stLabelNames.PwrEngO_Index = find(strcmp('PwrEngO',stLabelNames.Labels));   %Find PwrEngO in Data (kW)
        stLabelNames.PwrEngIn_Index = find(strcmp('PwrEngIn',stLabelNames.Labels));   %Find PwrEngO in Data (kW)
        
        
    %Fuel Rate
        stLabelNames.Mfuel_Index = find(strcmp('Mfuel',stLabelNames.Labels));
        stLabelNames.Qfuel_Index = find(strcmp('Qfuel',stLabelNames.Labels));
    
        
    %Time
        stLabelNames.Time_Index = find(strcmp('Time',stLabelNames.Labels));
        
    %Tire Forces
    
        switch NUMAXLES
            
            case 2
                stLabelNames.Fz_L1_Index = find(strcmp('Fz_L1',stLabelNames.Labels));
                stLabelNames.Fz_R1_Index = find(strcmp('Fz_R1',stLabelNames.Labels));
                stLabelNames.Fz_L2_Index = find(strcmp('Fz_L2',stLabelNames.Labels));
                stLabelNames.Fz_R2_Index = find(strcmp('Fz_R2',stLabelNames.Labels));
        
                stLabelNames.Fz_A1_Index = find(strcmp('Fz_A1',stLabelNames.Labels));
                stLabelNames.Fz_A2_Index = find(strcmp('Fz_A2',stLabelNames.Labels));
                
                
            case 3
                
                stLabelNames.Fz_L1_Index = find(strcmp('Fz_L1',stLabelNames.Labels));
                stLabelNames.Fz_R1_Index = find(strcmp('Fz_R1',stLabelNames.Labels));
                stLabelNames.Fz_L2_Index = find(strcmp('Fz_L2',stLabelNames.Labels));
                stLabelNames.Fz_R2_Index = find(strcmp('Fz_R2',stLabelNames.Labels));
                stLabelNames.Fz_L3_Index = find(strcmp('Fz_L3',stLabelNames.Labels));
                stLabelNames.Fz_R3_Index = find(strcmp('Fz_R3',stLabelNames.Labels));
        
                stLabelNames.Fz_A1_Index = find(strcmp('Fz_A1',stLabelNames.Labels));
                stLabelNames.Fz_A2_Index = find(strcmp('Fz_A2',stLabelNames.Labels));
                stLabelNames.Fz_A3_Index = find(strcmp('Fz_A3',stLabelNames.Labels));
                
            case 4
                
                
                %stLabelNames.Fz_L1_Index = find(strcmp('Fz_A4',stLabelNames.Labels));
                
            case 5
                
                
        end
        
    %User Input Devices
        stLabelNames.Bk_Stat_Index = find(strcmp('Bk_Stat',stLabelNames.Labels));
        stLabelNames.Pbk_Con_Index = find(strcmp('Pbk_Con',stLabelNames.Labels));
        stLabelNames.Throttle_Index = find(strcmp('Throttle',stLabelNames.Labels));
        
    %Vehicle Acceleration
        stLabelNames.Ax_Index = find(strcmp('Ax',stLabelNames.Labels));
        stLabelNames.Ay_Index = find(strcmp('Ay',stLabelNames.Labels));
        stLabelNames.Az_Index = find(strcmp('Az',stLabelNames.Labels));
    
    %Vehicle Position
        stLabelNames.Xo_Index = find(strcmp('Xo',stLabelNames.Labels));
        stLabelNames.Yo_Index = find(strcmp('Yo',stLabelNames.Labels));
        stLabelNames.Zo_Index = find(strcmp('Zo',stLabelNames.Labels));
        
    %Vehicle Velocity
        stLabelNames.Vx_Index = find(strcmp('Vx',stLabelNames.Labels));
        stLabelNames.Vy_Index = find(strcmp('Vy',stLabelNames.Labels));
        stLabelNames.Vz_Index = find(strcmp('Vz',stLabelNames.Labels));
    
%     Data.B = {'Time';'AAx';'AAy';'AAy_L1';'AAy_L2';'AAy_R1';'AAy_R2';'AAz';'AA_Eng';'AA_P';'AA_R';'AA_Y';'AlphaL1i';'AlphaL1o';'AlphaL2i';...
%         'AlphaL2o';'AlphaR1i';'AlphaR1o';'AlphaR2i';'AlphaR2o';'AlphLL1i';'AlphLL1o';'AlphLL2i';'AlphLL2o';'AlphLR1i';'AlphLR1o';'AlphLR2i';...
%         'AlphLR2o';'AVx';'AVx_L1';'AVx_L2';'AVx_R1';'AVx_R2';'AVy';'AVy_L1';'AVy_L2';'AVy_R1';'AVy_R2';'AVy_W_L1';'AVy_W_L2';'AVy_W_R1';...
%         'AVy_W_R2';'AVz';'AVz_L1';'AVz_L2';'AVz_R1';'AVz_R2';'AV_D3f';'AV_D3r';'AV_DS_L1';'AV_DS_L2';'AV_DS_R1';'AV_DS_R2';'AV_Eng';'AV_P';...
%         'AV_R';'AV_TC';'AV_Trans';'AV_Y';'Ax';'Ax_Rd';'Ax_SCrq';'Ax_SM';'Ay';'Ay_Rd';'Ay_SM';'Az';'Az_Rd';'Az_SM';'A_Comp';'A_Speedo';...
%         'A_Tach';'Beta';'BetaAir';'BetaR';'BetaRd';'BetaRdR';'Bk_Stat';'CamberL1';'CamberL2';'CamberR1';'CamberR2';'Clt_D1_2';'Clt_D2_2';...
%         'Clt_D3_2';'ClutchD1';'ClutchD2';'ClutchD3';'ClutchL1';'ClutchL2';'ClutchR1';'ClutchR2';'ClutchTr';'cl_stat';'CmpAD_L1';'CmpAD_L2';...
%         'CmpAD_R1';'CmpAD_R2';'CmpD_L1';'CmpD_L2';'CmpD_R1';'CmpD_R2';'CmpJStL1';'CmpJStL2';'CmpJStR1';'CmpJStR2';'CmpRD_L1';'CmpRD_L2';...
%         'CmpRD_R1';'CmpRD_R2';'CmpRStL1';'CmpRStL2';'CmpRStR1';'CmpRStR2';'CmpS_L1';'CmpS_L2';'CmpS_R1';'CmpS_R2';'CmpT_L1i';'CmpT_L1o';...
%         'CmpT_L2i';'CmpT_L2o';'CmpT_R1i';'CmpT_R1o';'CmpT_R2i';'CmpT_R2o';'dZdXair';'dZdX_L1i';'dZdX_L1o';'dZdX_L2i';'dZdX_L2o';'dZdX_R1i';...
%         'dZdX_R1o';'dZdX_R2i';'dZdX_R2o';'dZdYair';'dZdY_L1i';'dZdY_L1o';'dZdY_L2i';'dZdY_L2o';'dZdY_R1i';'dZdY_R1o';'dZdY_R2i';'dZdY_R2o';...
%         'Event';'Fd_L1';'Fd_L2';'Fd_R1';'Fd_R2';'FJSt_L1';'FJSt_L2';'FJSt_R1';'FJSt_R2';'FRSt_L1';'FRSt_L2';'FRSt_R1';'FRSt_R2';'FsExt_L1';...
%         'FsExt_L2';'FsExt_R1';'FsExt_R2';'Fs_L1';'Fs_L2';'Fs_R1';'Fs_R2';'FullStep';'FxExA1';'FxExA2';'FxGExA1';'FxGExA2';'Fx_A1';'Fx_A2';...
%         'Fx_Air';'Fx_L1';'Fx_L1i';'Fx_L1o';'Fx_L2';'Fx_L2i';'Fx_L2o';'Fx_R1';'Fx_R1i';'Fx_R1o';'Fx_R2';'Fx_R2i';'Fx_R2o';'Fx_Wc_L1';...
%         'Fx_Wc_L2';'Fx_Wc_R1';'Fx_Wc_R2';'FyExA1';'FyExA2';'FyGExA1';'FyGExA2';'Fy_A1';'Fy_A2';'Fy_Air';'Fy_L1';'Fy_L1i';'Fy_L1o';'Fy_L2';...
%         'Fy_L2i';'Fy_L2o';'Fy_R1';'Fy_R1i';'Fy_R1o';'Fy_R2';'Fy_R2i';'Fy_R2o';'Fy_Wc_L1';'Fy_Wc_L2';'Fy_Wc_R1';'Fy_Wc_R2';'FzExA1';'FzExA2';...
%         'FzGExA1';'FzGExA2';'Fz_A1';'Fz_A2';'Fz_Air';'Fz_L1';'Fz_L1i';'Fz_L1o';'Fz_L2';'Fz_L2i';'Fz_L2o';'Fz_R1';'Fz_R1i';'Fz_R1o';'Fz_R2';...
%         'Fz_R2i';'Fz_R2o';'Fz_Wc_L1';'Fz_Wc_L2';'Fz_Wc_R1';'Fz_Wc_R2';'f_mod';'GammaL1i';'GammaL1o';'GammaL2i';'GammaL2o';'GammaR1i';...
%         'GammaR1o';'GammaR2i';'GammaR2o';'GearStat';'Gear_CL';'Gear_OL';'GPSlongA';'GPS_Lat';'GPS_LatA';'GPS_Long';'ID_Event';'ID_Run';...
%         'Ispin_Tr';'Iw_Dr_L1';'Iw_Dr_L2';'Iw_Dr_R1';'Iw_Dr_R2';'JncA_A1';'JncA_A2';'JncR_A1';'JncR_A2';'Jnc_L1';'Jnc_L2';'Jnc_R1';'Jnc_R2';...
%         'JounceA1';'JounceA2';'KappaL1i';'KappaL1o';'KappaL2i';'KappaL2o';'KappaR1i';'KappaR1o';'KappaR2i';'KappaR2o';'KappLL1i';'KappLL1o';...
%         'KappLL2i';'KappLL2o';'KappLR1i';'KappLR1o';'KappLR2i';'KappLR2o';'Ksf_Gnd';'Ksf_StrR';'Kug_Gnd';'Kug_StrR';'K_TC';'Lat_Targ';...
%         'Lat_Veh';'Mfuel';'mod1L1i';'mod1R1i';'mod2L1i';'mod2R1i';'mod3L1i';'mod3R1i';'mod4L1i';'mod4R1i';'ModeTran';'MuX_L1i';'MuX_L1o';...
%         'MuX_L2i';'MuX_L2o';'MuX_R1i';'MuX_R1o';'MuX_R2i';'MuX_R2o';'MuY_L1i';'MuY_L1o';'MuY_L2i';'MuY_L2o';'MuY_R1i';'MuY_R1o';'MuY_R2i';...
%         'MuY_R2o';'MxExA1';'MxExA2';'MxGExA1';'MxGExA2';'MXGEXT';'Mx_A1';'Mx_A2';'Mx_Air';'MX_EXT';'Mx_L1';'Mx_L1i';'Mx_L1o';'Mx_L2';...
%         'Mx_L2i';'Mx_L2o';'Mx_R1';'Mx_R1i';'Mx_R1o';'Mx_R2';'Mx_R2i';'Mx_R2o';'Mx_Wc_L1';'Mx_Wc_L2';'Mx_Wc_R1';'Mx_Wc_R2';'MyExA1';...
%         'MyExA2';'MyGExA1';'MyGExA2';'MYGEXT';'MyRR_L1i';'MyRR_L1o';'MyRR_L2i';'MyRR_L2o';'MyRR_R1i';'MyRR_R1o';'MyRR_R2i';'MyRR_R2o';...
%         'My_Air';'My_Bk_L1';'My_Bk_L2';'My_Bk_R1';'My_Bk_R2';'My_Dr_L1';'My_Dr_L2';'My_Dr_R1';'My_Dr_R2';'MY_EXT';'My_RR_L1';'My_RR_L2';...
%         'My_RR_R1';'My_RR_R2';'My_US_L1';'My_US_L2';'My_US_R1';'My_US_R2';'My_Wc_L1';'My_Wc_L2';'My_Wc_R1';'My_Wc_R2';'MzExA1';'MzExA2';...
%         'MzGExA1';'MzGExA2';'MZGEXT';'Mz_Air';'MZ_EXT';'Mz_KP_L1';'Mz_KP_L2';'Mz_KP_R1';'Mz_KP_R2';'Mz_L1';'Mz_L1i';'Mz_L1o';'Mz_L2';...
%         'Mz_L2i';'Mz_L2o';'Mz_R1';'Mz_R1i';'Mz_R1o';'Mz_R2';'Mz_R2i';'Mz_R2o';'Mz_Wc_L1';'Mz_Wc_L2';'Mz_Wc_R1';'Mz_Wc_R2';'M_Clutch';...
%         'M_Cl_Cap';'M_D1visc';'M_D1_Cl';'M_D1_Cl2';'M_D2visc';'M_D2_Cl';'M_D2_Cl2';'M_D3f';'M_D3r';'M_D3visc';'M_D3_Cl';'M_D3_Cl2';...
%         'M_EngOut';'M_Eng_In';'M_L1_Cl';'M_L2_Cl';'M_R1_Cl';'M_R2_Cl';'M_SW';'M_TC';'M_Trans';'PbkCh_L1';'PbkCh_L2';'PbkCh_R1';'PbkCh_R2';...
%         'PbkD_L1';'PbkD_L2';'PbkD_R1';'PbkD_R2';'Pbk_Con';'Pitch';'PitchGL1';'PitchGL2';'PitchGR1';'PitchGR2';'PitchRd';'Pitch_A1';...
%         'Pitch_A2';'Pitch_L1';'Pitch_L2';'Pitch_R1';'Pitch_R2';'PtchPath';'PtchShad';'PwrEngAv';'PwrEngIn';'PwrEngO';'PwrTrans';...
%         'PwrWheel';'Pwr_SC';'Pwr_SCrq';'Pwr_TC';'Qfuel';'Rgear_Tr';'RhoPathY';'RhoPathZ';'Rho_Road';'RolA_A1r';'RolA_A2r';'Roll';...
%         'RollGL1';'RollGL2';'RollGR1';'RollGR2';'RollPath';'RollShad';'Roll_A1';'Roll_A1r';'Roll_A2';'Roll_A2r';'Roll_E';'Roll_L1';...
%         'Roll_L2';'Roll_R1';'Roll_R2';'Roll_Rd';'RolR_A1r';'RolR_A2r';'RotTrans';'Rot_D3f';'Rot_D3r';'Rot_Eng';'Rot_L1';'Rot_L2';...
%         'Rot_R1';'Rot_R2';'Rot_TC';'R_AV_TC';'R_M_TC';'Station';'Sta_Prof';'Sta_Road';'Steer_L1';'Steer_L2';'Steer_R1';'Steer_R2';...
%         'Steer_SW';'StrAV_SW';'StrBp_A1';'StrBp_A2';'StrC_L1';'StrC_L2';'StrC_R1';'StrC_R2';'StrK_L1';'StrK_L2';'StrK_R1';'StrK_R2';...
%         'StrR_A1';'StrR_A2';'StrSWr_1';'StrSWr_2';'StrWp_A1';'StrWp_A2';'TC_Lock';'Throttle';'Thrtl_SC';'Thr_Eng';'Thr_Intl';'T_Event';...
%         'T_Stamp';'Vair';'VJStL1';'VJStL2';'VJStR1';'VJStR2';'VRStL1';'VRStL2';'VRStR1';'VRStR2';'Vwind';'Vx';'VxCenL1i';'VxCenL1o';...
%         'VxCenL2i';'VxCenL2o';'VxCenR1i';'VxCenR1o';'VxCenR2i';'VxCenR2o';'VxNf_SM';'VxTarget';'Vx_Err';'Vx_IErr';'Vx_L1';'Vx_L2';...
%         'Vx_R1';'Vx_R2';'Vx_Rd';'Vx_SM';'Vx_Wc_L1';'Vx_Wc_L2';'Vx_Wc_R1';'Vx_Wc_R2';'Vy';'VyNf_SM';'VyTC_L1i';'VyTC_L1o';'VyTC_L2i';...
%         'VyTC_L2o';'VyTC_R1i';'VyTC_R1o';'VyTC_R2i';'VyTC_R2o';'Vy_Rd';'Vy_SM';'Vy_Wc_L1';'Vy_Wc_L2';'Vy_Wc_R1';'Vy_Wc_R2';'Vz';'Vz_Rd';...
%         'Vz_SM';'Vz_Wc_L1';'Vz_Wc_L2';'Vz_Wc_R1';'Vz_Wc_R2';'v_mod1';'v_mod2';'v_mod3';'v_mod4';'XCG_SM';'XCG_TM';'Xctc_L1i';'Xctc_L1o';...
%         'Xctc_L2i';'Xctc_L2o';'Xctc_R1i';'Xctc_R1o';'Xctc_R2i';'Xctc_R2o';'Xo';'Xrd_Air';'X_A1';'X_A2';'X_camF';'X_camR';'X_Design';...
%         'X_L1';'X_L2';'X_R1';'X_R2';'X_Target';'Yaw';'Yaw_CamF';'Yaw_CamR';'Yaw_L1';'Yaw_L2';'Yaw_R1';'Yaw_R2';'Yaw_Wind';'YCG_SM';...
%         'YCG_TM';'Yctc_L1i';'Yctc_L1o';'Yctc_L2i';'Yctc_L2o';'Yctc_R1i';'Yctc_R1o';'Yctc_R2i';'Yctc_R2o';'Yo';'Yrd_Air';'Y_A1';'Y_A2';...
%         'Y_camF';'Y_camR';'Y_Design';'Y_L1';'Y_L2';'Y_R1';'Y_R2';'Y_Target';'ZCG_SM';'ZCG_TM';'Zgnd_L1i';'Zgnd_L1o';'Zgnd_L2i';...
%         'Zgnd_L2o';'Zgnd_R1i';'Zgnd_R1o';'Zgnd_R2i';'Zgnd_R2o';'Zo';'Zrd_Air';'Z_A1';'Z_A2';'Z_camF';'Z_camR';'Z_L1';'Z_L2';'Z_R1';...
%         'Z_R2';'Z_Shadow'};


end

